name: Build Repo
on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Repo Package
        run: |
          # هنا بنصنع الملف في الواجهة الرئيسية مباشرة بدون مجلد repo
          echo '{"name": "ProChan Repo", "author": "Bill", "packages": [{"name": "ProManga", "pkg": "eu.kanade.tachiyomi.extension.ar.promanga", "apk": "promanga.apk", "versionCode": 1, "versionName": "1.0", "nsfw": 0, "lang": "ar"}]}' > index.min.json
          echo "fake apk" > promanga.apk
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # النشر في الواجهة الرئيسية مباشرة
          branch: repo-pages
